### ISSUE TITLE
bug in search box

### ISSUE THREAD

**Issue by SeemWind** [KJZH001/doc-mc#9]
![IMG_0205](https://github.com/KJZH001/doc-mc/assets/50366675/11bae089-4f73-4b56-93d1-585a5547f837)

search box show html code in result

**Comment by KJZH001** [comment]
对于程序而言，这应该不是bug，html标签正常来说也不应该出现在标题的位置

为何要嵌套使用html的标题标签？

markdown本身解析渲染后已经带有了页面锚点

**Comment by SeemWind** [comment]
那颜色呢
